version: "3.9"
services:
  mongodb:
    image: mongo:6.0
    container_name: "${MONGO_CONTAINER_NAME}"
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: